package site.letsgoapp.letsgo.testingUtility.fakes.fakeClientSourceIntermediate

import requestmessages.RequestMessages.ServerActivityOrCategoryMessage

fun setupLoginCategoriesList(): List<ServerActivityOrCategoryMessage> {
    val categoriesList = mutableListOf<ServerActivityOrCategoryMessage>()

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(0)
            .setOrderNumber(0.0)
            .setDisplayName("Unknown")
            .setIconDisplayName("")
            .setMinAge(121)
            .setColor("#000000")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(1)
            .setOrderNumber(1.0)
            .setDisplayName("Pick-Up Sports")
            .setIconDisplayName("")
            .setMinAge(13)
            .setColor("#a5002d")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(2)
            .setOrderNumber(2.0)
            .setDisplayName("Working Out")
            .setIconDisplayName("")
            .setMinAge(13)
            .setColor("#c83d00")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(3)
            .setOrderNumber(3.0)
            .setDisplayName("Food")
            .setIconDisplayName("")
            .setMinAge(13)
            .setColor("#228B22")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(4)
            .setOrderNumber(4.0)
            .setDisplayName("Adventures")
            .setIconDisplayName("")
            .setMinAge(13)
            .setColor("#2188ff")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(5)
            .setOrderNumber(5.0)
            .setDisplayName("Social Drinking & Tastings")
            .setIconDisplayName("")
            .setMinAge(21)
            .setColor("#ff5f42")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(6)
            .setOrderNumber(6.0)
            .setDisplayName("Sporting Entertainment")
            .setIconDisplayName("")
            .setMinAge(13)
            .setColor("#9e64b4")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(7)
            .setOrderNumber(7.0)
            .setDisplayName("Play Dates")
            .setIconDisplayName("")
            .setMinAge(18)
            .setColor("#5aa900")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(8)
            .setOrderNumber(8.0)
            .setDisplayName("Beauty")
            .setIconDisplayName("")
            .setMinAge(13)
            .setColor("#FF1694")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(9)
            .setOrderNumber(9.0)
            .setDisplayName("Concerts")
            .setIconDisplayName("")
            .setMinAge(13)
            .setColor("#003a8d")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(10)
            .setOrderNumber(10.0)
            .setDisplayName("Poker")
            .setIconDisplayName("")
            .setMinAge(18)
            .setColor("#b4554b")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(11)
            .setOrderNumber(11.0)
            .setDisplayName("Collectable Card Games")
            .setIconDisplayName("")
            .setMinAge(13)
            .setColor("#a400b3")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(12)
            .setOrderNumber(12.0)
            .setDisplayName("Movies & TV")
            .setIconDisplayName("")
            .setMinAge(13)
            .setColor("#c7953d")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(13)
            .setOrderNumber(13.0)
            .setDisplayName("Personal Development")
            .setIconDisplayName("")
            .setMinAge(13)
            .setColor("#6500ff")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(14)
            .setOrderNumber(14.0)
            .setDisplayName("Video Games")
            .setIconDisplayName("")
            .setMinAge(13)
            .setColor("#0d35f9")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(15)
            .setOrderNumber(15.0)
            .setDisplayName("DIY")
            .setIconDisplayName("")
            .setMinAge(13)
            .setColor("#fe6400")
            .build()
    )

    categoriesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(16)
            .setOrderNumber(16.0)
            .setDisplayName("Board Games")
            .setIconDisplayName("")
            .setMinAge(13)
            .setColor("#e555ff")
            .build()
    )

    return categoriesList
}

fun setupLoginActivitiesList(): List<ServerActivityOrCategoryMessage> {
    val activitiesList = mutableListOf<ServerActivityOrCategoryMessage>()

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(0)
            .setDisplayName("Unknown")
            .setIconDisplayName("Unknown")
            .setMinAge(13)
            .setCategoryIndex(0)
            .setIconIndex(0)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(1)
            .setDisplayName("Baseball")
            .setIconDisplayName("Baseball")
            .setMinAge(13)
            .setCategoryIndex(1)
            .setIconIndex(1)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(2)
            .setDisplayName("Basketball")
            .setIconDisplayName("Basketball")
            .setMinAge(13)
            .setCategoryIndex(1)
            .setIconIndex(2)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(3)
            .setDisplayName("Football")
            .setIconDisplayName("Football")
            .setMinAge(13)
            .setCategoryIndex(1)
            .setIconIndex(3)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(4)
            .setDisplayName("Golf")
            .setIconDisplayName("Golf")
            .setMinAge(13)
            .setCategoryIndex(1)
            .setIconIndex(4)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(5)
            .setDisplayName("Hockey")
            .setIconDisplayName("Hockey")
            .setMinAge(13)
            .setCategoryIndex(1)
            .setIconIndex(5)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(6)
            .setDisplayName("Soccer")
            .setIconDisplayName("Soccer")
            .setMinAge(13)
            .setCategoryIndex(1)
            .setIconIndex(6)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(7)
            .setDisplayName("Ultimate Frisbee")
            .setIconDisplayName("Ultimate Frisbee")
            .setMinAge(13)
            .setCategoryIndex(1)
            .setIconIndex(7)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(8)
            .setDisplayName("Volleyball")
            .setIconDisplayName("Volleyball")
            .setMinAge(13)
            .setCategoryIndex(1)
            .setIconIndex(8)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(9)
            .setDisplayName("Crossfit")
            .setIconDisplayName("Crossfit")
            .setMinAge(13)
            .setCategoryIndex(2)
            .setIconIndex(9)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(10)
            .setDisplayName("Cycling")
            .setIconDisplayName("Cycling")
            .setMinAge(13)
            .setCategoryIndex(2)
            .setIconIndex(10)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(11)
            .setDisplayName("Dance")
            .setIconDisplayName("Dance")
            .setMinAge(13)
            .setCategoryIndex(2)
            .setIconIndex(11)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(12)
            .setDisplayName("MMA")
            .setIconDisplayName("MMA")
            .setMinAge(13)
            .setCategoryIndex(2)
            .setIconIndex(12)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(13)
            .setDisplayName("Pilates")
            .setIconDisplayName("Pilates")
            .setMinAge(13)
            .setCategoryIndex(2)
            .setIconIndex(13)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(14)
            .setDisplayName("Running")
            .setIconDisplayName("Running")
            .setMinAge(13)
            .setCategoryIndex(2)
            .setIconIndex(14)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(15)
            .setDisplayName("Swimming")
            .setIconDisplayName("Swimming")
            .setMinAge(13)
            .setCategoryIndex(2)
            .setIconIndex(15)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(16)
            .setDisplayName("Weight Training")
            .setIconDisplayName("Weight Training")
            .setMinAge(13)
            .setCategoryIndex(2)
            .setIconIndex(16)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(17)
            .setDisplayName("Yoga")
            .setIconDisplayName("Yoga")
            .setMinAge(13)
            .setCategoryIndex(2)
            .setIconIndex(17)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(18)
            .setDisplayName("American")
            .setIconDisplayName("American")
            .setMinAge(13)
            .setCategoryIndex(3)
            .setIconIndex(18)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(19)
            .setDisplayName("Brunch")
            .setIconDisplayName("Brunch")
            .setMinAge(13)
            .setCategoryIndex(3)
            .setIconIndex(19)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(20)
            .setDisplayName("Chinese")
            .setIconDisplayName("Chinese")
            .setMinAge(13)
            .setCategoryIndex(3)
            .setIconIndex(20)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(21)
            .setDisplayName("Indian")
            .setIconDisplayName("Indian")
            .setMinAge(13)
            .setCategoryIndex(3)
            .setIconIndex(21)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(22)
            .setDisplayName("Italian")
            .setIconDisplayName("Italian")
            .setMinAge(13)
            .setCategoryIndex(3)
            .setIconIndex(22)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(23)
            .setDisplayName("Mexican")
            .setIconDisplayName("Mexican")
            .setMinAge(13)
            .setCategoryIndex(3)
            .setIconIndex(23)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(24)
            .setDisplayName("Pho")
            .setIconDisplayName("Pho")
            .setMinAge(13)
            .setCategoryIndex(3)
            .setIconIndex(24)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(25)
            .setDisplayName("Sushi")
            .setIconDisplayName("Sushi")
            .setMinAge(13)
            .setCategoryIndex(3)
            .setIconIndex(25)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(26)
            .setDisplayName("Thai")
            .setIconDisplayName("Thai")
            .setMinAge(13)
            .setCategoryIndex(3)
            .setIconIndex(26)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(27)
            .setDisplayName("Band Jam Session")
            .setIconDisplayName("Band Jam Session")
            .setMinAge(13)
            .setCategoryIndex(4)
            .setIconIndex(27)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(28)
            .setDisplayName("Bar Hopping")
            .setIconDisplayName("Bar Hopping")
            .setMinAge(21)
            .setCategoryIndex(4)
            .setIconIndex(28)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(29)
            .setDisplayName("Boating")
            .setIconDisplayName("Boating")
            .setMinAge(13)
            .setCategoryIndex(4)
            .setIconIndex(29)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(30)
            .setDisplayName("Clubbing")
            .setIconDisplayName("Clubbing")
            .setMinAge(21)
            .setCategoryIndex(4)
            .setIconIndex(30)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(31)
            .setDisplayName("Dancing")
            .setIconDisplayName("Dancing")
            .setMinAge(13)
            .setCategoryIndex(4)
            .setIconIndex(31)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(32)
            .setDisplayName("Hiking")
            .setIconDisplayName("Hiking")
            .setMinAge(13)
            .setCategoryIndex(4)
            .setIconIndex(32)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(33)
            .setDisplayName("Shopping")
            .setIconDisplayName("Shopping")
            .setMinAge(13)
            .setCategoryIndex(4)
            .setIconIndex(33)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(34)
            .setDisplayName("Skiing")
            .setIconDisplayName("Skiing")
            .setMinAge(13)
            .setCategoryIndex(4)
            .setIconIndex(34)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(35)
            .setDisplayName("Snowboarding")
            .setIconDisplayName("Snow-\nboarding")
            .setMinAge(13)
            .setCategoryIndex(4)
            .setIconIndex(35)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(36)
            .setDisplayName("Water Activities")
            .setIconDisplayName("Water Activities")
            .setMinAge(13)
            .setCategoryIndex(4)
            .setIconIndex(36)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(37)
            .setDisplayName("Beer")
            .setIconDisplayName("Beer")
            .setMinAge(21)
            .setCategoryIndex(5)
            .setIconIndex(37)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(38)
            .setDisplayName("Spirits")
            .setIconDisplayName("Spirits")
            .setMinAge(21)
            .setCategoryIndex(5)
            .setIconIndex(38)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(39)
            .setDisplayName("Wine")
            .setIconDisplayName("Wine")
            .setMinAge(21)
            .setCategoryIndex(5)
            .setIconIndex(39)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(40)
            .setDisplayName("Baseball")
            .setIconDisplayName("Baseball")
            .setMinAge(13)
            .setCategoryIndex(6)
            .setIconIndex(1)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(41)
            .setDisplayName("Basketball")
            .setIconDisplayName("Basketball")
            .setMinAge(13)
            .setCategoryIndex(6)
            .setIconIndex(2)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(42)
            .setDisplayName("Boxing")
            .setIconDisplayName("Boxing")
            .setMinAge(13)
            .setCategoryIndex(6)
            .setIconIndex(40)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(43)
            .setDisplayName("Football")
            .setIconDisplayName("Football")
            .setMinAge(13)
            .setCategoryIndex(6)
            .setIconIndex(3)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(44)
            .setDisplayName("Golf")
            .setIconDisplayName("Golf")
            .setMinAge(13)
            .setCategoryIndex(6)
            .setIconIndex(4)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(45)
            .setDisplayName("Hockey")
            .setIconDisplayName("Hockey")
            .setMinAge(13)
            .setCategoryIndex(6)
            .setIconIndex(5)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(46)
            .setDisplayName("MMA")
            .setIconDisplayName("MMA")
            .setMinAge(13)
            .setCategoryIndex(6)
            .setIconIndex(12)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(47)
            .setDisplayName("Soccer")
            .setIconDisplayName("Soccer")
            .setMinAge(13)
            .setCategoryIndex(6)
            .setIconIndex(6)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(48)
            .setDisplayName("Tennis")
            .setIconDisplayName("Tennis")
            .setMinAge(13)
            .setCategoryIndex(6)
            .setIconIndex(41)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(49)
            .setDisplayName("Hair")
            .setIconDisplayName("Hair")
            .setMinAge(13)
            .setCategoryIndex(8)
            .setIconIndex(42)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(50)
            .setDisplayName("Makeup")
            .setIconDisplayName("Makeup")
            .setMinAge(13)
            .setCategoryIndex(8)
            .setIconIndex(43)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(51)
            .setDisplayName("Mani Pedi")
            .setIconDisplayName("Mani Pedi")
            .setMinAge(13)
            .setCategoryIndex(8)
            .setIconIndex(44)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(52)
            .setDisplayName("Skin Care")
            .setIconDisplayName("Skin Care")
            .setMinAge(13)
            .setCategoryIndex(8)
            .setIconIndex(45)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(53)
            .setDisplayName("Board Games")
            .setIconDisplayName("Board Games")
            .setMinAge(18)
            .setCategoryIndex(7)
            .setIconIndex(46)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(54)
            .setDisplayName("Crafts")
            .setIconDisplayName("Crafts")
            .setMinAge(18)
            .setCategoryIndex(7)
            .setIconIndex(47)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(55)
            .setDisplayName("Fun In The Kitchen")
            .setIconDisplayName("Fun In The Kitchen")
            .setMinAge(18)
            .setCategoryIndex(7)
            .setIconIndex(48)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(56)
            .setDisplayName("Movies")
            .setIconDisplayName("Movies")
            .setMinAge(18)
            .setCategoryIndex(7)
            .setIconIndex(49)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(57)
            .setDisplayName("Outings")
            .setIconDisplayName("Outings")
            .setMinAge(18)
            .setCategoryIndex(7)
            .setIconIndex(50)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(58)
            .setDisplayName("Park Day")
            .setIconDisplayName("Park Day")
            .setMinAge(18)
            .setCategoryIndex(7)
            .setIconIndex(51)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(59)
            .setDisplayName("Country")
            .setIconDisplayName("Country")
            .setMinAge(13)
            .setCategoryIndex(9)
            .setIconIndex(52)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(60)
            .setDisplayName("EDM")
            .setIconDisplayName("EDM")
            .setMinAge(13)
            .setCategoryIndex(9)
            .setIconIndex(53)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(61)
            .setDisplayName("Hip-Hop")
            .setIconDisplayName("Hip-Hop")
            .setMinAge(13)
            .setCategoryIndex(9)
            .setIconIndex(54)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(62)
            .setDisplayName("Indie")
            .setIconDisplayName("Indie")
            .setMinAge(13)
            .setCategoryIndex(9)
            .setIconIndex(55)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(63)
            .setDisplayName("Jazz")
            .setIconDisplayName("Jazz")
            .setMinAge(13)
            .setCategoryIndex(9)
            .setIconIndex(56)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(64)
            .setDisplayName("Oldies")
            .setIconDisplayName("Oldies")
            .setMinAge(13)
            .setCategoryIndex(9)
            .setIconIndex(57)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(65)
            .setDisplayName("Pop")
            .setIconDisplayName("Pop")
            .setMinAge(13)
            .setCategoryIndex(9)
            .setIconIndex(58)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(66)
            .setDisplayName("Rap")
            .setIconDisplayName("Rap")
            .setMinAge(13)
            .setCategoryIndex(9)
            .setIconIndex(59)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(67)
            .setDisplayName("Rock")
            .setIconDisplayName("Rock")
            .setMinAge(13)
            .setCategoryIndex(9)
            .setIconIndex(60)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(68)
            .setDisplayName("5 Card Draw")
            .setIconDisplayName("5 Card Draw")
            .setMinAge(18)
            .setCategoryIndex(10)
            .setIconIndex(61)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(69)
            .setDisplayName("7 Card Stud")
            .setIconDisplayName("7 Card Stud")
            .setMinAge(18)
            .setCategoryIndex(10)
            .setIconIndex(62)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(70)
            .setDisplayName("Blind Man's Bluff")
            .setIconDisplayName("Blind Man's Bluff")
            .setMinAge(18)
            .setCategoryIndex(10)
            .setIconIndex(63)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(71)
            .setDisplayName("Omaha Hold'em")
            .setIconDisplayName("Omaha Hold'em")
            .setMinAge(18)
            .setCategoryIndex(10)
            .setIconIndex(64)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(72)
            .setDisplayName("Texas Hold'em")
            .setIconDisplayName("Texas Hold'em")
            .setMinAge(18)
            .setCategoryIndex(10)
            .setIconIndex(65)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(73)
            .setDisplayName("Magic The Gathering")
            .setIconDisplayName("Magic The Gathering")
            .setMinAge(13)
            .setCategoryIndex(11)
            .setIconIndex(66)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(74)
            .setDisplayName("Pokemon")
            .setIconDisplayName("Pokemon")
            .setMinAge(13)
            .setCategoryIndex(11)
            .setIconIndex(67)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(75)
            .setDisplayName("Yu-Gi-Oh!")
            .setIconDisplayName("Yu-Gi-Oh!")
            .setMinAge(13)
            .setCategoryIndex(11)
            .setIconIndex(68)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(76)
            .setDisplayName("Action/Adventure")
            .setIconDisplayName("Action / Adventure")
            .setMinAge(13)
            .setCategoryIndex(12)
            .setIconIndex(69)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(77)
            .setDisplayName("Comedy")
            .setIconDisplayName("Comedy")
            .setMinAge(13)
            .setCategoryIndex(12)
            .setIconIndex(70)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(78)
            .setDisplayName("Drama")
            .setIconDisplayName("Drama")
            .setMinAge(13)
            .setCategoryIndex(12)
            .setIconIndex(71)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(79)
            .setDisplayName("Reality TV")
            .setIconDisplayName("Reality TV")
            .setMinAge(13)
            .setCategoryIndex(12)
            .setIconIndex(72)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(80)
            .setDisplayName("Thriller/Suspense")
            .setIconDisplayName("Thriller / Suspense")
            .setMinAge(13)
            .setCategoryIndex(12)
            .setIconIndex(73)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(81)
            .setDisplayName("Emotional")
            .setIconDisplayName("Emotional")
            .setMinAge(13)
            .setCategoryIndex(13)
            .setIconIndex(74)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(82)
            .setDisplayName("Intellectual")
            .setIconDisplayName("Intellectual")
            .setMinAge(13)
            .setCategoryIndex(13)
            .setIconIndex(75)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(83)
            .setDisplayName("Investing & Finances")
            .setIconDisplayName("Investing & Finances")
            .setMinAge(13)
            .setCategoryIndex(13)
            .setIconIndex(76)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(84)
            .setDisplayName("Relational")
            .setIconDisplayName("Relational")
            .setMinAge(13)
            .setCategoryIndex(13)
            .setIconIndex(77)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(85)
            .setDisplayName("Battle Royale")
            .setIconDisplayName("Battle Royale")
            .setMinAge(13)
            .setCategoryIndex(14)
            .setIconIndex(78)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(86)
            .setDisplayName("Digital Card Games")
            .setIconDisplayName("Digital Card Games")
            .setMinAge(13)
            .setCategoryIndex(14)
            .setIconIndex(79)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(87)
            .setDisplayName("FPS")
            .setIconDisplayName("FPS")
            .setMinAge(13)
            .setCategoryIndex(14)
            .setIconIndex(80)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(88)
            .setDisplayName("MMORPG")
            .setIconDisplayName("MMORPG")
            .setMinAge(13)
            .setCategoryIndex(14)
            .setIconIndex(81)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(89)
            .setDisplayName("MOBA")
            .setIconDisplayName("MOBA")
            .setMinAge(13)
            .setCategoryIndex(14)
            .setIconIndex(82)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(90)
            .setDisplayName("Racing")
            .setIconDisplayName("Racing")
            .setMinAge(13)
            .setCategoryIndex(14)
            .setIconIndex(83)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(91)
            .setDisplayName("Sports")
            .setIconDisplayName("Sports")
            .setMinAge(13)
            .setCategoryIndex(14)
            .setIconIndex(84)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(92)
            .setDisplayName("Cars")
            .setIconDisplayName("Cars")
            .setMinAge(13)
            .setCategoryIndex(15)
            .setIconIndex(85)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(93)
            .setDisplayName("Home Care")
            .setIconDisplayName("Home Care")
            .setMinAge(13)
            .setCategoryIndex(15)
            .setIconIndex(86)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(94)
            .setDisplayName("Item Refurbishment")
            .setIconDisplayName("Refurbish Items")
            .setMinAge(13)
            .setCategoryIndex(15)
            .setIconIndex(87)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(95)
            .setDisplayName("Antique Restoration")
            .setIconDisplayName("Restore Antiques")
            .setMinAge(13)
            .setCategoryIndex(15)
            .setIconIndex(88)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(96)
            .setDisplayName("Catan")
            .setIconDisplayName("Catan")
            .setMinAge(13)
            .setCategoryIndex(16)
            .setIconIndex(89)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(97)
            .setDisplayName("Checkers")
            .setIconDisplayName("Checkers")
            .setMinAge(13)
            .setCategoryIndex(16)
            .setIconIndex(90)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(98)
            .setDisplayName("Chess")
            .setIconDisplayName("Chess")
            .setMinAge(13)
            .setCategoryIndex(16)
            .setIconIndex(91)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(99)
            .setDisplayName("Dominoes")
            .setIconDisplayName("Dominoes")
            .setMinAge(13)
            .setCategoryIndex(16)
            .setIconIndex(92)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(100)
            .setDisplayName("Dungeons & Dragons")
            .setIconDisplayName("Dungeons & Dragons")
            .setMinAge(13)
            .setCategoryIndex(16)
            .setIconIndex(93)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(101)
            .setDisplayName("Monopoly")
            .setIconDisplayName("Monopoly")
            .setMinAge(13)
            .setCategoryIndex(16)
            .setIconIndex(94)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(102)
            .setDisplayName("Pictionary")
            .setIconDisplayName("Pictionary")
            .setMinAge(13)
            .setCategoryIndex(16)
            .setIconIndex(95)
            .build()
    )

    activitiesList.add(
        ServerActivityOrCategoryMessage.newBuilder()
            .setIndex(103)
            .setDisplayName("Scrabble")
            .setIconDisplayName("Scrabble")
            .setMinAge(13)
            .setCategoryIndex(16)
            .setIconIndex(96)
            .build()
    )

    return activitiesList
}
